name: Node.js CI

on:
  # push:
  #   branches: [ "main" ]
  pull_request:
    # branches: [ "main, dev" ]
    branches: '*' # ← this means: ON EVERY PULL-REQUEST of ANY BRANCH

jobs:
  Version-check:
    runs-on: ubuntu-latest
    name: Bump-N-Tag Version
    steps:
    - uses: actions/checkout@master
    - name: Increment version
      id: version   
      uses: vinodhraj/Bump-N-Tag-Version@master
      with:
        file_name: './VERSION'
        tag_version: "true"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
