name: Release creator
#docs: https://github.com/marketplace/actions/semver-release-manager
# The action will parse the new commits since the last tag using pattern #release-{BumpType}

#Example:
#(PATCH) git commit -m "this is a patch release #release-patch" 
#(MINOR) git commit -m "this is a patch release #release-minor" 
#(MAJOR) git commit -m "this is a patch release #release-major" 

# on:
  # pull_request:
  #   branches: [ "main" ] 
on:
  push:
    # branches: [ master ]
    branches: [ main ]
jobs:
  manage_release_job:
    runs-on: ubuntu-latest
    name: Generate release
    steps:
    - name: Generate release
      id: release
      uses: home-furnishing-nordic/semver-release-manager@master
      with:
        # secret github token, required
        github_token: "${{ secrets.GITHUB_TOKEN }}"
    # Use the output from the `release` step
    - name: Get the output time
      run: echo "Execution time ${{ steps.release.outputs.time }}"